2025-07-16 13:07:58 [scrapy.utils.log] INFO: Scrapy 2.12.0 started (bot: crawler)
2025-07-16 13:07:59 [scrapy.utils.log] INFO: Versions: lxml 5.4.0.0, libxml2 2.13.8, cssselect 1.3.0, parsel 1.10.0, w3lib 2.3.1, Twisted 25.5.0, Python 3.13.3 (main, Apr 10 2025, 21:38:51) [GCC 14.2.0], pyOpenSSL 25.1.0 (OpenSSL 3.5.0 8 Apr 2025), cryptography 45.0.4, Platform Linux-6.12.25-amd64-x86_64-with-glibc2.41
2025-07-16 13:07:59 [scrapy.addons] INFO: Enabled addons:
[]
2025-07-16 13:07:59 [scrapy.extensions.telnet] INFO: Telnet Password: 56feaef56db4a97c
2025-07-16 13:07:59 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
2025-07-16 13:07:59 [scrapy.crawler] INFO: Overridden settings:
{'AUTOTHROTTLE_ENABLED': True,
 'AUTOTHROTTLE_MAX_DELAY': 10,
 'AUTOTHROTTLE_START_DELAY': 1,
 'AUTOTHROTTLE_TARGET_CONCURRENCY': 2.0,
 'BOT_NAME': 'crawler',
 'DOWNLOAD_DELAY': 2.3217625238289656,
 'DOWNLOAD_TIMEOUT': 45,
 'HTTPCACHE_ENABLED': '1',
 'HTTPCACHE_EXPIRATION_SECS': '0',
 'HTTPCACHE_STORAGE': 'scrapy.extensions.httpcache.LeveldbCacheStorage',
 'LOG_FILE': 'out.log',
 'LOG_LEVEL': 'INFO',
 'LOG_STDOUT': 'False',
 'NEWSPIDER_MODULE': 'crawler.spiders',
 'RANDOMIZE_DOWNLOAD_DELAY': 0.5,
 'RETRY_TIMES': 8,
 'SPIDER_LOADER_WARN_ONLY': True,
 'SPIDER_MODULES': ['crawler.spiders'],
 'USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, '
               'like Gecko) Chrome/120.0.0.0 Safari/537.36'}
2025-07-16 13:07:59 [twisted] CRITICAL: Unhandled error in Deferred:
2025-07-16 13:07:59 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/utils/misc.py", line 74, in load_object
    obj = getattr(mod, name)
AttributeError: module 'scrapy.extensions.httpcache' has no attribute 'LeveldbCacheStorage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
                  ~~~~~~~~~~~~~~~~~~~^^
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/core/engine.py", line 101, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
                                  ~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/core/downloader/__init__.py", line 109, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/middleware.py", line 88, in _from_settings
    mw = build_from_crawler(mwcls, crawler)
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/utils/misc.py", line 187, in build_from_crawler
    instance = objcls.from_crawler(crawler, *args, **kwargs)  # type: ignore[attr-defined]
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 59, in from_crawler
    o = cls(crawler.settings, crawler.stats)
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 52, in __init__
    self.storage = load_object(settings["HTTPCACHE_STORAGE"])(settings)
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vector/darknet_crawler/tor-env/lib/python3.13/site-packages/scrapy/utils/misc.py", line 76, in load_object
    raise NameError(f"Module '{module}' doesn't define any object named '{name}'")
NameError: Module 'scrapy.extensions.httpcache' doesn't define any object named 'LeveldbCacheStorage'
